// <auto-generated />
using System;
using CurrencyExchange.Infrastructure.persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CurrencyExchange.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CurrencyExchange.Core.Entities.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("CurrencyExchange.Core.Entities.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Currencies");
                });

            modelBuilder.Entity("CurrencyExchange.Core.Entities.ExchangeRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CurrencyId")
                        .HasColumnType("int");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("RateDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.ToTable("ExchangeRates");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            CurrencyId = 2,
                            Rate = 3.10906273643777m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 3,
                            CurrencyId = 3,
                            Rate = 2.20677351034542m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 4,
                            CurrencyId = 4,
                            Rate = 3.00968953070038m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 5,
                            CurrencyId = 5,
                            Rate = 1.28286579952763m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 6,
                            CurrencyId = 6,
                            Rate = 4.73241625597295m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 7,
                            CurrencyId = 7,
                            Rate = 2.33465120760191m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 8,
                            CurrencyId = 8,
                            Rate = 2.87321103015725m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 9,
                            CurrencyId = 9,
                            Rate = 3.68744791210937m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 10,
                            CurrencyId = 10,
                            Rate = 2.44203286171903m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 11,
                            CurrencyId = 11,
                            Rate = 0.679459315172407m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 12,
                            CurrencyId = 12,
                            Rate = 4.54408764759618m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 13,
                            CurrencyId = 13,
                            Rate = 2.77091019896015m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 14,
                            CurrencyId = 14,
                            Rate = 3.6861609808514m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 15,
                            CurrencyId = 15,
                            Rate = 4.59657963407007m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 16,
                            CurrencyId = 16,
                            Rate = 0.479912314074555m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 17,
                            CurrencyId = 17,
                            Rate = 1.64219645944794m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 18,
                            CurrencyId = 18,
                            Rate = 2.13736169216426m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 19,
                            CurrencyId = 19,
                            Rate = 1.41138551926071m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 20,
                            CurrencyId = 20,
                            Rate = 1.2664043376501m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 21,
                            CurrencyId = 21,
                            Rate = 1.42912840276687m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 22,
                            CurrencyId = 22,
                            Rate = 0.40877859174434m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 23,
                            CurrencyId = 23,
                            Rate = 0.254191091534968m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 24,
                            CurrencyId = 24,
                            Rate = 4.54131276912296m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 25,
                            CurrencyId = 25,
                            Rate = 1.57239481043227m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 26,
                            CurrencyId = 26,
                            Rate = 2.75376061370111m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 27,
                            CurrencyId = 27,
                            Rate = 1.67385912894313m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 28,
                            CurrencyId = 28,
                            Rate = 1.37441798464971m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 29,
                            CurrencyId = 29,
                            Rate = 0.934759622811983m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 30,
                            CurrencyId = 30,
                            Rate = 4.20161852860976m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 31,
                            CurrencyId = 31,
                            Rate = 1.81310352624636m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 32,
                            CurrencyId = 32,
                            Rate = 4.09192290661505m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 33,
                            CurrencyId = 33,
                            Rate = 1.72811122013143m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 34,
                            CurrencyId = 34,
                            Rate = 4.81251084871594m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 35,
                            CurrencyId = 35,
                            Rate = 2.87199712715661m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 36,
                            CurrencyId = 36,
                            Rate = 2.02547570637429m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 37,
                            CurrencyId = 37,
                            Rate = 0.967056690538911m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 38,
                            CurrencyId = 38,
                            Rate = 1.49133923157405m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 39,
                            CurrencyId = 39,
                            Rate = 3.20644804536966m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 40,
                            CurrencyId = 40,
                            Rate = 1.0333121043688m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 41,
                            CurrencyId = 41,
                            Rate = 4.72827340888611m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 42,
                            CurrencyId = 42,
                            Rate = 0.724130850556486m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 43,
                            CurrencyId = 43,
                            Rate = 2.34673215320424m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 44,
                            CurrencyId = 44,
                            Rate = 4.69321136239854m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 45,
                            CurrencyId = 45,
                            Rate = 0.134411604356578m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 46,
                            CurrencyId = 46,
                            Rate = 0.861775513482116m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 47,
                            CurrencyId = 47,
                            Rate = 2.74567004157034m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 48,
                            CurrencyId = 48,
                            Rate = 3.59870064089773m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 49,
                            CurrencyId = 49,
                            Rate = 0.627520460378172m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 50,
                            CurrencyId = 50,
                            Rate = 2.51495730203972m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 51,
                            CurrencyId = 51,
                            Rate = 0.242970245052201m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 52,
                            CurrencyId = 52,
                            Rate = 4.07256339209025m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 53,
                            CurrencyId = 53,
                            Rate = 0.651625889060478m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 54,
                            CurrencyId = 54,
                            Rate = 1.50883555453461m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 55,
                            CurrencyId = 55,
                            Rate = 2.59562873106598m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 56,
                            CurrencyId = 56,
                            Rate = 4.22423675721788m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 57,
                            CurrencyId = 57,
                            Rate = 0.411372200972897m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 58,
                            CurrencyId = 58,
                            Rate = 1.31686246023245m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 59,
                            CurrencyId = 59,
                            Rate = 2.25952316762643m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 60,
                            CurrencyId = 60,
                            Rate = 4.66940969394515m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 61,
                            CurrencyId = 61,
                            Rate = 1.37682892081193m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 62,
                            CurrencyId = 62,
                            Rate = 0.78759161325198m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 63,
                            CurrencyId = 63,
                            Rate = 3.3962145104598m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 64,
                            CurrencyId = 64,
                            Rate = 0.625323459848366m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 65,
                            CurrencyId = 65,
                            Rate = 0.790616426919934m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 66,
                            CurrencyId = 66,
                            Rate = 1.8888213838908m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 67,
                            CurrencyId = 67,
                            Rate = 3.4399215257372m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 68,
                            CurrencyId = 68,
                            Rate = 4.57763821929794m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 69,
                            CurrencyId = 69,
                            Rate = 4.73806725429302m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 70,
                            CurrencyId = 70,
                            Rate = 1.22003922141353m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 71,
                            CurrencyId = 71,
                            Rate = 3.71568918408838m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 72,
                            CurrencyId = 72,
                            Rate = 0.977160937916796m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 73,
                            CurrencyId = 73,
                            Rate = 3.27280117231631m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 74,
                            CurrencyId = 74,
                            Rate = 4.91807861542696m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 75,
                            CurrencyId = 75,
                            Rate = 4.53296781734065m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 76,
                            CurrencyId = 76,
                            Rate = 4.98855970949784m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 77,
                            CurrencyId = 77,
                            Rate = 1.59933760226525m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 78,
                            CurrencyId = 78,
                            Rate = 2.73174633187427m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 79,
                            CurrencyId = 79,
                            Rate = 1.83375121458197m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 80,
                            CurrencyId = 80,
                            Rate = 2.45742155143474m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 81,
                            CurrencyId = 81,
                            Rate = 3.71064027693744m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 82,
                            CurrencyId = 82,
                            Rate = 1.0135364307212m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 83,
                            CurrencyId = 83,
                            Rate = 4.3673967245815m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 84,
                            CurrencyId = 84,
                            Rate = 2.8038339124165m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 85,
                            CurrencyId = 85,
                            Rate = 2.5458134721685m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 86,
                            CurrencyId = 86,
                            Rate = 2.23024787616632m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 87,
                            CurrencyId = 87,
                            Rate = 1.11208257682911m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 88,
                            CurrencyId = 88,
                            Rate = 2.82422426393774m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 89,
                            CurrencyId = 89,
                            Rate = 2.82402110718128m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 90,
                            CurrencyId = 90,
                            Rate = 3.29260511864361m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 91,
                            CurrencyId = 91,
                            Rate = 2.05352085264721m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 92,
                            CurrencyId = 92,
                            Rate = 4.4065733101966m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 93,
                            CurrencyId = 93,
                            Rate = 1.12320554634926m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 94,
                            CurrencyId = 94,
                            Rate = 4.58915266019754m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 95,
                            CurrencyId = 95,
                            Rate = 2.56766887490947m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 96,
                            CurrencyId = 96,
                            Rate = 2.8325393383771m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 97,
                            CurrencyId = 97,
                            Rate = 1.37080595093836m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 98,
                            CurrencyId = 98,
                            Rate = 2.79568550040534m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 99,
                            CurrencyId = 99,
                            Rate = 2.11060513565144m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 100,
                            CurrencyId = 100,
                            Rate = 2.60023199094346m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 101,
                            CurrencyId = 101,
                            Rate = 3.61888997618037m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 102,
                            CurrencyId = 102,
                            Rate = 0.711525398331667m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 103,
                            CurrencyId = 103,
                            Rate = 0.683844349960806m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 104,
                            CurrencyId = 104,
                            Rate = 3.5951409547108m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 105,
                            CurrencyId = 105,
                            Rate = 1.32291279995323m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 106,
                            CurrencyId = 106,
                            Rate = 0.302676270921078m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 107,
                            CurrencyId = 107,
                            Rate = 2.16178690014144m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 108,
                            CurrencyId = 108,
                            Rate = 3.64055875142537m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 109,
                            CurrencyId = 109,
                            Rate = 0.64564239306695m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 110,
                            CurrencyId = 110,
                            Rate = 0.441251675764839m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 111,
                            CurrencyId = 111,
                            Rate = 4.66003576569786m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 112,
                            CurrencyId = 112,
                            Rate = 1.06409164334284m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 113,
                            CurrencyId = 113,
                            Rate = 4.56945859593762m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 114,
                            CurrencyId = 114,
                            Rate = 2.96877778285222m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 115,
                            CurrencyId = 115,
                            Rate = 2.77492910535288m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 116,
                            CurrencyId = 116,
                            Rate = 4.00077226432333m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 117,
                            CurrencyId = 117,
                            Rate = 4.62086115253918m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 118,
                            CurrencyId = 118,
                            Rate = 4.50481303135266m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 119,
                            CurrencyId = 119,
                            Rate = 1.97034029669919m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 120,
                            CurrencyId = 120,
                            Rate = 1.60650438743769m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 121,
                            CurrencyId = 121,
                            Rate = 0.160301861577799m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 122,
                            CurrencyId = 122,
                            Rate = 2.96538496808015m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 123,
                            CurrencyId = 123,
                            Rate = 1.27415427654748m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 124,
                            CurrencyId = 124,
                            Rate = 1.13767660041966m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 125,
                            CurrencyId = 125,
                            Rate = 1.29381275542791m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 126,
                            CurrencyId = 126,
                            Rate = 1.78419147249295m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 127,
                            CurrencyId = 127,
                            Rate = 1.85429044621958m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 128,
                            CurrencyId = 128,
                            Rate = 3.32857882043955m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 129,
                            CurrencyId = 129,
                            Rate = 1.51568543335708m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 130,
                            CurrencyId = 130,
                            Rate = 3.67197833795606m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 131,
                            CurrencyId = 131,
                            Rate = 4.11600737692805m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 132,
                            CurrencyId = 132,
                            Rate = 2.88706975833474m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 133,
                            CurrencyId = 133,
                            Rate = 0.548668548649108m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 134,
                            CurrencyId = 134,
                            Rate = 0.38808681854864m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 135,
                            CurrencyId = 135,
                            Rate = 3.8390684495516m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 136,
                            CurrencyId = 136,
                            Rate = 3.61750392736615m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 137,
                            CurrencyId = 137,
                            Rate = 0.534937398342536m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 138,
                            CurrencyId = 138,
                            Rate = 4.69626009187946m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 139,
                            CurrencyId = 139,
                            Rate = 0.95642463108357m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 140,
                            CurrencyId = 140,
                            Rate = 2.85656711539815m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 141,
                            CurrencyId = 141,
                            Rate = 3.15360378393565m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 142,
                            CurrencyId = 142,
                            Rate = 2.68446681470776m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 143,
                            CurrencyId = 143,
                            Rate = 3.39905173376744m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 144,
                            CurrencyId = 144,
                            Rate = 2.45775749112876m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 145,
                            CurrencyId = 145,
                            Rate = 4.59104428748119m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 146,
                            CurrencyId = 146,
                            Rate = 3.50798267473602m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 147,
                            CurrencyId = 147,
                            Rate = 4.87762192276893m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 148,
                            CurrencyId = 148,
                            Rate = 2.33595484465068m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 149,
                            CurrencyId = 149,
                            Rate = 2.14762849194632m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 150,
                            CurrencyId = 150,
                            Rate = 4.73104379759539m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 151,
                            CurrencyId = 151,
                            Rate = 2.0222139726074m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 152,
                            CurrencyId = 152,
                            Rate = 0.781813109196488m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 153,
                            CurrencyId = 153,
                            Rate = 2.15894797207643m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 154,
                            CurrencyId = 154,
                            Rate = 3.96855876791665m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 155,
                            CurrencyId = 155,
                            Rate = 4.70853238449199m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 156,
                            CurrencyId = 156,
                            Rate = 3.01557089532936m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 157,
                            CurrencyId = 157,
                            Rate = 4.75026953593514m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 158,
                            CurrencyId = 158,
                            Rate = 3.52761440560379m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 159,
                            CurrencyId = 159,
                            Rate = 1.1722849746909m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 160,
                            CurrencyId = 160,
                            Rate = 3.67740739843685m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 161,
                            CurrencyId = 161,
                            Rate = 3.88102858290465m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 162,
                            CurrencyId = 162,
                            Rate = 0.341735651620813m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 163,
                            CurrencyId = 163,
                            Rate = 1.78691457207997m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 164,
                            CurrencyId = 164,
                            Rate = 3.2756555563626m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 165,
                            CurrencyId = 165,
                            Rate = 2.92055071717442m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 166,
                            CurrencyId = 166,
                            Rate = 2.00595782161374m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 167,
                            CurrencyId = 167,
                            Rate = 4.18107109839573m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 168,
                            CurrencyId = 168,
                            Rate = 0.198591981319527m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 169,
                            CurrencyId = 169,
                            Rate = 1.34042174816959m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 170,
                            CurrencyId = 170,
                            Rate = 1.16023195062669m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 171,
                            CurrencyId = 171,
                            Rate = 2.49178702156632m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 172,
                            CurrencyId = 172,
                            Rate = 2.33259687687024m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 173,
                            CurrencyId = 173,
                            Rate = 1.11403328484311m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 174,
                            CurrencyId = 174,
                            Rate = 3.66859247627037m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 175,
                            CurrencyId = 175,
                            Rate = 1.0451534722353m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 176,
                            CurrencyId = 176,
                            Rate = 0.678338572433554m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 177,
                            CurrencyId = 177,
                            Rate = 3.13335934141951m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 178,
                            CurrencyId = 178,
                            Rate = 2.86143205415754m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 179,
                            CurrencyId = 179,
                            Rate = 2.03778263547498m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 180,
                            CurrencyId = 180,
                            Rate = 3.25979147890237m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 181,
                            CurrencyId = 181,
                            Rate = 4.95774224994424m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 182,
                            CurrencyId = 182,
                            Rate = 2.18877706307837m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 183,
                            CurrencyId = 183,
                            Rate = 1.7425408343909m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 184,
                            CurrencyId = 184,
                            Rate = 2.12282008305162m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 185,
                            CurrencyId = 185,
                            Rate = 4.76210121065345m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 186,
                            CurrencyId = 186,
                            Rate = 1.11628878741927m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 187,
                            CurrencyId = 187,
                            Rate = 2.62456431712507m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 188,
                            CurrencyId = 188,
                            Rate = 2.60140934251884m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 189,
                            CurrencyId = 189,
                            Rate = 0.12714073642812m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 190,
                            CurrencyId = 190,
                            Rate = 0.785081476861366m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 191,
                            CurrencyId = 191,
                            Rate = 4.18587562816684m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 192,
                            CurrencyId = 192,
                            Rate = 1.6241194976274m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 193,
                            CurrencyId = 193,
                            Rate = 1.31021968166894m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 194,
                            CurrencyId = 194,
                            Rate = 1.26971683888786m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 195,
                            CurrencyId = 195,
                            Rate = 4.29342176923638m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 196,
                            CurrencyId = 196,
                            Rate = 2.33404447944197m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 197,
                            CurrencyId = 197,
                            Rate = 3.60544967888397m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 198,
                            CurrencyId = 198,
                            Rate = 3.44502628295032m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 199,
                            CurrencyId = 199,
                            Rate = 3.56590275014844m,
                            RateDate = new DateOnly(2025, 2, 19)
                        },
                        new
                        {
                            Id = 200,
                            CurrencyId = 200,
                            Rate = 2.30711777737395m,
                            RateDate = new DateOnly(2025, 2, 19)
                        });
                });

            modelBuilder.Entity("CurrencyExchange.Core.Entities.Country", b =>
                {
                    b.HasOne("CurrencyExchange.Core.Entities.Currency", "Currency")
                        .WithMany("Countries")
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Currency");
                });

            modelBuilder.Entity("CurrencyExchange.Core.Entities.ExchangeRate", b =>
                {
                    b.HasOne("CurrencyExchange.Core.Entities.Currency", "Currency")
                        .WithMany("ExchangeRates")
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Currency");
                });

            modelBuilder.Entity("CurrencyExchange.Core.Entities.Currency", b =>
                {
                    b.Navigation("Countries");

                    b.Navigation("ExchangeRates");
                });
#pragma warning restore 612, 618
        }
    }
}
